import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import type { ProjectMap } from "../analyzers/pipeline/index.js";
import { isSnapshotStale, readSnapshotOrThrow } from "../cache/snapshot.js";
import { buildOnboardingModel } from "../onboarding/modelBuilder.js";
import type { OnboardingLanguage, OnboardingModel, KeyFlow, ConceptualStep, FeatureSummary, StartHereItem } from "../onboarding/model.js";
import { output, withJsonOutput } from "../utils/output.js";
import { createPrompt, type Prompt } from "../utils/prompt.js";

export type { OnboardingLanguage } from "../onboarding/model.js";

export type OnboardingOptions = {
  json?: boolean;
  language?: string;
  projectRoot?: string;
  prompt?: Prompt;
  target?: string;
  write?: boolean;
};

export type OnboardingGuide = {
  status: "ok";
  language: OnboardingLanguage;
  projectName: string;
  tagline: string;
  stackLine: string;
  whatThisIs: string;
  howItWorks: ConceptualStep[];
  features: FeatureSummary[];
  startHere: StartHereItem[];
  keyFlows: KeyFlow[];
  snapshot: {
    generatedAt: string;
    stale: boolean;
  };
  markdown: string;
  writtenPath: string | null;
};

export async function onboardingCommand(options: OnboardingOptions = {}): Promise<void> {
  if (options.json) {
    await withJsonOutput(async () => {
      output.json(await runOnboarding(options));
    });
    return;
  }

  const guide = await runOnboarding(options);
  output.section("DevMap Onboarding");
  if (guide.snapshot.stale) {
    output.warning("Snapshot is stale: this guide may use outdated project structure.");
    output.note("Run devmap analyze --fresh, then repeat devmap onboarding.");
  }
  output.markdown(guide.markdown);

  if (guide.writtenPath) {
    output.success(`Wrote ${guide.writtenPath}`);
  } else {
    output.note("To write this guide to ONBOARDING.md, run devmap onboarding --write.");
  }
}

async function runOnboarding(options: OnboardingOptions): Promise<OnboardingGuide> {
  const projectRoot = resolve(options.projectRoot ?? options.target ?? ".");
  const snapshot = await readSnapshotOrThrow(projectRoot);
  const stale = await isSnapshotStale(projectRoot, snapshot);
  const language = await resolveOnboardingLanguage(options);
  const model = buildOnboardingModel(snapshot, language);
  model.isStale = stale;

  const keyFlows = buildKeyFlows(snapshot);
  const markdown = buildOnboardingMarkdown(model, { stale, language, keyFlows });
  const writtenPath = options.write ? "ONBOARDING.md" : null;

  if (writtenPath) {
    await writeFile(join(projectRoot, writtenPath), `${markdown}\n`, "utf8");
  }

  return {
    status: "ok",
    language,
    projectName: model.projectName,
    tagline: model.tagline,
    stackLine: model.stackLine,
    whatThisIs: model.whatThisIs,
    howItWorks: model.howItWorks,
    features: model.features,
    startHere: model.startHere,
    keyFlows: model.isStale ? [] : keyFlows,
    snapshot: {
      generatedAt: snapshot.generatedAt,
      stale
    },
    markdown,
    writtenPath
  };
}

function buildKeyFlows(snapshot: ProjectMap): KeyFlow[] {
  return snapshot.flows.slice(0, 3).map((flow) => ({
    name: flow.name,
    steps: flow.steps.slice(0, 8).map((step) => ({
      file: step.file ?? step.label,
      what: step.purpose ?? step.label,
    })),
  }));
}

export function buildOnboardingMarkdown(
  model: OnboardingModel,
  options: {
    stale?: boolean;
    language?: OnboardingLanguage;
    keyFlows?: KeyFlow[];
  } = {}
): string {
  const language = options.language ?? model.language;
  const guide = getGuideLabels(language);
  const sections = [
    `# ${model.projectName}`,
    "",
    model.tagline,
    "",
    model.stackLine,
    "",
    ...(options.stale ? [
      guide.staleNote,
      ""
    ] : []),
    `## ${guide.whatThisIs}`,
    "",
    model.whatThisIs,
    "",
    `## ${guide.howItWorks}`,
    "",
    ...renderHowItWorks(model.howItWorks),
    "",
    `## ${guide.whatsInside}`,
    "",
    ...renderFeatures(model.features),
    "",
    `## ${guide.startHere}`,
    "",
    ...renderStartHere(model.startHere),
    "",
    ...(options.keyFlows && options.keyFlows.length > 0
      ? [
          `## ${guide.keyFlows}`,
          "",
          ...renderKeyFlows(options.keyFlows),
          ""
        ]
      : []),
    `## ${guide.goDeeper}`,
    "",
    ...renderGoDeeper(language),
    "",
    language === "id"
      ? "---\n_Dibuat oleh DevMap dari `.devmap/snapshot.json`._"
      : "---\n_Generated by DevMap from `.devmap/snapshot.json`._"
  ];

  return sections.join("\n").replace(/\n{3,}/g, "\n\n");
}

function renderHowItWorks(steps: ConceptualStep[]): string[] {
  if (steps.length === 0) return [];
  return steps.map((step, index) => `${index + 1}. ${step.step}`);
}

function renderFeatures(features: FeatureSummary[]): string[] {
  if (features.length === 0) return [];
  return features.map((f) => {
    const entry = f.entryFile ? ` — mulai dari \`${f.entryFile}\`` : "";
    return `- **${f.name}**: ${f.what}${entry}`;
  });
}

function renderStartHere(items: StartHereItem[]): string[] {
  if (items.length === 0) {
    return [];
  }
  return items.map((item) => `${item.order}. \`${item.path}\` — ${item.reason}`);
}

function renderKeyFlows(flows: KeyFlow[]): string[] {
  return flows.flatMap((flow) => [
    `### ${flow.name}`,
    "",
    ...flow.steps.flatMap((step, i) => [
      `${"  ".repeat(1)}${i + 1}. \`${step.file}\``,
      `${"  ".repeat(2)}${step.what}`,
    ]),
    ""
  ]);
}

function renderGoDeeper(language: OnboardingLanguage): string[] {
  if (language === "id") {
    return [
      "- `devmap explain <file>` — pahami apa yang dilakukan sebuah file",
      "- `devmap map` — lihat peta struktur dan dependency penuh",
      "- `devmap flow` — telusuri alur request dari awal sampai akhir",
    ];
  }

  return [
    "- `devmap explain <file>` — understand what a specific file does",
    "- `devmap map` — see the full dependency and structure map",
    "- `devmap flow` — trace a request end-to-end",
  ];
}

// ── Language resolution ───────────────────────────────────────────────────────

async function resolveOnboardingLanguage(options: OnboardingOptions): Promise<OnboardingLanguage> {
  const explicitLanguage = normalizeOnboardingLanguage(options.language);
  if (explicitLanguage) {
    return explicitLanguage;
  }

  if (!options.write || options.json || (!options.prompt && !process.stdin.isTTY)) {
    return "en";
  }

  const prompt = options.prompt ?? createPrompt();

  try {
    const answer = await prompt.ask(
      "Onboarding language? [en/id] (default: en): "
    );
    return normalizeOnboardingLanguage(answer) ?? "en";
  } finally {
    prompt.close();
  }
}

function normalizeOnboardingLanguage(value: string | undefined): OnboardingLanguage | null {
  const normalized = value?.trim().toLowerCase();
  if (!normalized) {
    return null;
  }

  if (["id", "indo", "indonesia", "bahasa indonesia"].includes(normalized)) {
    return "id";
  }
  if (["en", "eng", "english", "inggris"].includes(normalized)) {
    return "en";
  }

  return null;
}

// ── Language labels ──────────────────────────────────────────────────────────

function getGuideLabels(language: OnboardingLanguage) {
  if (language === "id") {
    return {
      staleNote: "> Snapshot ini stale. Jalankan `devmap analyze --fresh` sebelum memakai guide ini untuk keputusan penting.",
      whatThisIs: "Apa Ini",
      howItWorks: "Cara Kerja",
      whatsInside: "Isi",
      startHere: "Mulai dari Sini",
      keyFlows: "Flow Penting",
      goDeeper: "Eksplorasi"
    };
  }

  return {
    staleNote: "> This snapshot is stale. Run `devmap analyze --fresh` before using this guide for important decisions.",
    whatThisIs: "What This Is",
    howItWorks: "How It Works",
    whatsInside: "What's Inside",
    startHere: "Start Here",
    keyFlows: "Key Flows",
    goDeeper: "Go Deeper"
  };
}
