import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import type { ProjectMap } from "../analyzers/projectMap.js";
import { isSnapshotStale, readSnapshotOrThrow } from "../cache/snapshot.js";
import { output, withJsonOutput } from "../utils/output.js";

export type OnboardingOptions = {
  json?: boolean;
  projectRoot?: string;
  target?: string;
  write?: boolean;
};

export type OnboardingGuide = {
  status: "ok";
  project: ProjectMap["project"];
  overview: string | null;
  snapshot: {
    generatedAt: string;
    stale: boolean;
  };
  agentInstructions: ProjectMap["agentInstructions"];
  entryPoints: string[];
  criticalFiles: ProjectMap["criticalFiles"];
  externalServices: string[];
  recommendedPath: string[];
  features: Array<{
    name: string;
    entryPoint: string | null;
    businessFlow: string[];
  }>;
  flows: Array<{
    name: string;
    type: ProjectMap["flows"][number]["type"];
    entryPoint: string | null;
    steps: string[];
  }>;
  changeImpact: ProjectMap["changeImpact"];
  markdown: string;
  writtenPath: string | null;
};

export async function onboardingCommand(options: OnboardingOptions = {}): Promise<void> {
  if (options.json) {
    await withJsonOutput(async () => {
      output.json(await runOnboarding(options));
    });
    return;
  }

  const guide = await runOnboarding(options);
  output.section("DevMap Onboarding");
  if (guide.snapshot.stale) {
    output.warning("Snapshot is stale: this guide may use outdated project structure.");
    output.note("Run devmap analyze --fresh, then repeat devmap onboarding.");
  }
  output.markdown(guide.markdown);

  if (guide.writtenPath) {
    output.success(`Wrote ${guide.writtenPath}`);
  }
}

async function runOnboarding(options: OnboardingOptions): Promise<OnboardingGuide> {
  const projectRoot = resolve(options.projectRoot ?? options.target ?? ".");
  const snapshot = await readSnapshotOrThrow(projectRoot);
  const stale = await isSnapshotStale(projectRoot, snapshot);
  const markdown = buildOnboardingMarkdown(snapshot, { stale });
  const writtenPath = options.write ? "ONBOARDING.md" : null;

  if (writtenPath) {
    await writeFile(join(projectRoot, writtenPath), `${markdown}\n`, "utf8");
  }

  return {
    status: "ok",
    project: snapshot.project,
    overview: snapshot.ai?.architecture ?? null,
    snapshot: {
      generatedAt: snapshot.generatedAt,
      stale
    },
    agentInstructions: snapshot.agentInstructions,
    entryPoints: snapshot.entryPoints,
    criticalFiles: snapshot.criticalFiles,
    externalServices: snapshot.externalServices,
    recommendedPath: snapshot.onboarding.recommendedPath,
    features: snapshot.features.map((feature) => ({
      name: feature.name,
      entryPoint: feature.entryPoint ?? null,
      businessFlow: feature.businessFlow
    })),
    flows: snapshot.flows.map((flow) => ({
      name: flow.name,
      type: flow.type,
      entryPoint: flow.entryPoint ?? null,
      steps: flow.steps.map((step) => step.file ?? step.label)
    })),
    changeImpact: snapshot.changeImpact,
    markdown,
    writtenPath
  };
}

export function buildOnboardingMarkdown(
  snapshot: ProjectMap,
  options: { stale?: boolean } = {}
): string {
  const sections = [
    "# Project Onboarding",
    "",
    "## Project Overview",
    "",
    `- Name: ${snapshot.project.name}`,
    `- Framework: ${snapshot.project.framework}`,
    `- Language: ${snapshot.project.language}`,
    `- Package manager: ${snapshot.project.packageManager}`,
    `- Files indexed: ${snapshot.stats.relevantFiles}`,
    `- Snapshot generated: ${snapshot.generatedAt}`,
    `- Snapshot status: ${options.stale ? "stale - run devmap analyze --fresh" : "fresh"}`,
    "",
    ...renderProjectNarrative(snapshot),
    "",
    "## Entry Points",
    "",
    ...renderList(snapshot.entryPoints),
    "",
    "## External Services",
    "",
    ...renderExternalServices(snapshot),
    "",
    "## Critical Files",
    "",
    ...renderCriticalFiles(snapshot),
    "",
    "## Recommended Reading Path",
    "",
    ...renderList(snapshot.onboarding.recommendedPath),
    "",
    "## Feature Map",
    "",
    ...renderFeatureMap(snapshot),
    "",
    "## Important Flows",
    "",
    ...renderFlows(snapshot),
    "",
    "## Change Impact Notes",
    "",
    ...renderChangeImpact(snapshot),
    "",
    "## Agent Workflow",
    "",
    ...renderAgentWorkflow(snapshot),
    "",
    "Generated by DevMap from `.devmap/snapshot.json`."
  ];

  return sections.join("\n").replace(/\n{3,}/g, "\n\n");
}

function renderAgentWorkflow(snapshot: ProjectMap): string[] {
  const instructions = snapshot.agentInstructions;
  return [
    `- Navigation policy: ${instructions.navigationPolicy}`,
    `- Default mode: ${instructions.defaultMode}`,
    `- Max initial files: ${instructions.maxInitialFiles}`,
    `- Missing snapshot action: ${instructions.missingSnapshotAction}`,
    `- Stale snapshot action: ${instructions.staleSnapshotAction}`,
    `- Fallback rule: ${instructions.fallbackRule}`,
    "",
    "Recommended sequence:",
    "1. Read `DEVMAP.md` first.",
    "2. Read `.devmap/snapshot.json` before broad repository exploration.",
    "3. Start with the recommended reading path and feature entry points.",
    "4. Inspect only the smallest source-file set needed for the task.",
    "5. Refresh the snapshot before relying on stale onboarding output."
  ];
}

function renderFeatureMap(snapshot: ProjectMap): string[] {
  if (snapshot.features.length === 0) {
    return ["No features detected yet."];
  }

  return snapshot.features.flatMap((feature) => [
    `### ${feature.name}`,
    "",
    `- Purpose: ${feature.purpose}`,
    ...renderOptionalPath("Entry point", feature.entryPoint),
    `- Confidence: ${feature.confidence}`,
    "",
    ...renderBusinessFlow(feature.businessFlow),
    ""
  ]);
}

function renderBusinessFlow(steps: string[]): string[] {
  if (steps.length === 0) {
    return ["- Business flow: not inferred yet"];
  }

  return [
    "- Business flow:",
    ...steps.map((step, index) => `  ${index + 1}. ${step}`)
  ];
}

function renderFlows(snapshot: ProjectMap): string[] {
  const flows = snapshot.flows.slice(0, 6);
  if (flows.length === 0) {
    return ["No flows detected yet."];
  }

  return flows.flatMap((flow) => [
    `### ${flow.name}`,
    "",
    `- Type: ${flow.type}`,
    ...renderOptionalPath("Entry point", flow.entryPoint),
    "",
    ...flow.steps.map((step, index) =>
      `${index + 1}. ${step.file ?? step.label}${step.purpose ? ` - ${step.purpose}` : ""}`
    ),
    ""
  ]);
}

function renderProjectNarrative(snapshot: ProjectMap): string[] {
  const featureNames = snapshot.features.map((feature) => feature.name);
  const services = snapshot.externalServices;
  const entryPoints = snapshot.entryPoints;
  const summary = [
    `${snapshot.project.name} is a ${snapshot.project.language} project`,
    `using ${snapshot.project.packageManager}`,
    snapshot.project.framework !== "unknown" ? `with ${snapshot.project.framework}` : null,
    entryPoints.length > 0 ? `starting from ${entryPoints[0]}` : null,
    featureNames.length > 0 ? `with detected feature areas such as ${formatInlineList(featureNames)}` : null,
    services.length > 0 ? `and external services such as ${formatInlineList(services)}` : null
  ].filter(Boolean).join(" ");

  const lines = [`${summary}.`];
  const architectureExcerpt = extractArchitectureExcerpt(snapshot.ai?.architecture);
  if (architectureExcerpt) {
    lines.push("", `Architecture note: ${architectureExcerpt}`);
  }

  return lines;
}

function renderExternalServices(snapshot: ProjectMap): string[] {
  if (snapshot.externalServices.length === 0) {
    return ["No external services detected yet."];
  }

  return snapshot.externalServices.map((service) => `- ${service}`);
}

function renderCriticalFiles(snapshot: ProjectMap): string[] {
  const files = snapshot.criticalFiles.slice(0, 10);
  if (files.length === 0) {
    return ["No critical files detected yet."];
  }

  return files.map((file, index) =>
    `${index + 1}. ${file.path} - score ${file.score}; ${file.reasons.join(", ")}`
  );
}

function renderOptionalPath(label: string, value: string | undefined): string[] {
  return value ? [`- ${label}: ${value}`] : [];
}

function extractArchitectureExcerpt(architecture: string | undefined): string | null {
  if (!architecture) {
    return null;
  }

  const text = architecture
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) =>
      line
      && !line.startsWith("#")
      && !line.startsWith("|")
      && !line.startsWith("---")
      && !/^[-*]\s/.test(line)
    )
    .join(" ")
    .replace(/[`*_]/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (text.length < 80) {
    return null;
  }

  return text.length > 500 ? `${text.slice(0, 497).trim()}...` : text;
}

function formatInlineList(values: string[]): string {
  const uniqueValues = [...new Set(values)].slice(0, 4);
  if (uniqueValues.length <= 1) {
    return uniqueValues[0] ?? "none";
  }

  return `${uniqueValues.slice(0, -1).join(", ")} and ${uniqueValues.at(-1)}`;
}

function renderChangeImpact(snapshot: ProjectMap): string[] {
  const entries = Object.entries(snapshot.changeImpact)
    .filter(([, impact]) => impact.impacts.length > 0)
    .slice(0, 8);

  if (entries.length === 0) {
    return ["No change impact metadata detected yet."];
  }

  return entries.map(([file, impact]) =>
    `- ${file}: impacts ${impact.impacts.join(", ")}`
  );
}

function renderList(values: string[]): string[] {
  if (values.length === 0) {
    return ["No recommended path detected yet."];
  }

  return values.map((value, index) => `${index + 1}. ${value}`);
}
