import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import type { ProjectMap } from "../analyzers/projectMap.js";
import { readSnapshotOrThrow } from "../cache/snapshot.js";
import { output, withJsonOutput } from "../utils/output.js";

export type OnboardingOptions = {
  json?: boolean;
  projectRoot?: string;
  target?: string;
  write?: boolean;
};

export type OnboardingGuide = {
  status: "ok";
  project: ProjectMap["project"];
  recommendedPath: string[];
  features: Array<{
    name: string;
    entryPoint: string | null;
    businessFlow: string[];
  }>;
  flows: Array<{
    name: string;
    type: ProjectMap["flows"][number]["type"];
    entryPoint: string | null;
    steps: string[];
  }>;
  changeImpact: ProjectMap["changeImpact"];
  markdown: string;
  writtenPath: string | null;
};

export async function onboardingCommand(options: OnboardingOptions = {}): Promise<void> {
  if (options.json) {
    await withJsonOutput(async () => {
      output.json(await runOnboarding(options));
    });
    return;
  }

  const guide = await runOnboarding(options);
  output.section("DevMap Onboarding");
  output.markdown(guide.markdown);

  if (guide.writtenPath) {
    output.success(`Wrote ${guide.writtenPath}`);
  }
}

async function runOnboarding(options: OnboardingOptions): Promise<OnboardingGuide> {
  const projectRoot = resolve(options.projectRoot ?? options.target ?? ".");
  const snapshot = await readSnapshotOrThrow(projectRoot);
  const markdown = buildOnboardingMarkdown(snapshot);
  const writtenPath = options.write ? "ONBOARDING.md" : null;

  if (writtenPath) {
    await writeFile(join(projectRoot, writtenPath), `${markdown}\n`, "utf8");
  }

  return {
    status: "ok",
    project: snapshot.project,
    recommendedPath: snapshot.onboarding.recommendedPath,
    features: snapshot.features.map((feature) => ({
      name: feature.name,
      entryPoint: feature.entryPoint ?? null,
      businessFlow: feature.businessFlow
    })),
    flows: snapshot.flows.map((flow) => ({
      name: flow.name,
      type: flow.type,
      entryPoint: flow.entryPoint ?? null,
      steps: flow.steps.map((step) => step.file ?? step.label)
    })),
    changeImpact: snapshot.changeImpact,
    markdown,
    writtenPath
  };
}

export function buildOnboardingMarkdown(snapshot: ProjectMap): string {
  const sections = [
    "# Project Onboarding",
    "",
    "## Project Overview",
    "",
    `- Name: ${snapshot.project.name}`,
    `- Framework: ${snapshot.project.framework}`,
    `- Language: ${snapshot.project.language}`,
    `- Package manager: ${snapshot.project.packageManager}`,
    `- Files indexed: ${snapshot.stats.relevantFiles}`,
    "",
    "## Recommended Reading Path",
    "",
    ...renderList(snapshot.onboarding.recommendedPath),
    "",
    "## Feature Map",
    "",
    ...renderFeatureMap(snapshot),
    "",
    "## Important Flows",
    "",
    ...renderFlows(snapshot),
    "",
    "## Change Impact Notes",
    "",
    ...renderChangeImpact(snapshot),
    "",
    "## Agent Workflow",
    "",
    "1. Read `DEVMAP.md` first.",
    "2. Read `.devmap/snapshot.json` before broad repository exploration.",
    "3. Start with the recommended reading path and feature entry points.",
    "4. Inspect only the smallest source-file set needed for the task.",
    "5. Run `devmap analyze --fresh` if the snapshot may be stale.",
    "",
    "Generated by DevMap from `.devmap/snapshot.json`."
  ];

  return sections.join("\n").replace(/\n{3,}/g, "\n\n");
}

function renderFeatureMap(snapshot: ProjectMap): string[] {
  if (snapshot.features.length === 0) {
    return ["No features detected yet."];
  }

  return snapshot.features.flatMap((feature) => [
    `### ${feature.name}`,
    "",
    `- Purpose: ${feature.purpose}`,
    `- Entry point: ${feature.entryPoint ?? "not inferred yet"}`,
    `- Confidence: ${feature.confidence}`,
    "",
    ...renderBusinessFlow(feature.businessFlow),
    ""
  ]);
}

function renderBusinessFlow(steps: string[]): string[] {
  if (steps.length === 0) {
    return ["- Business flow: not inferred yet"];
  }

  return [
    "- Business flow:",
    ...steps.map((step, index) => `  ${index + 1}. ${step}`)
  ];
}

function renderFlows(snapshot: ProjectMap): string[] {
  const flows = snapshot.flows.slice(0, 6);
  if (flows.length === 0) {
    return ["No flows detected yet."];
  }

  return flows.flatMap((flow) => [
    `### ${flow.name}`,
    "",
    `- Type: ${flow.type}`,
    `- Entry point: ${flow.entryPoint ?? "not inferred yet"}`,
    "",
    ...flow.steps.map((step, index) =>
      `${index + 1}. ${step.file ?? step.label}${step.purpose ? ` - ${step.purpose}` : ""}`
    ),
    ""
  ]);
}

function renderChangeImpact(snapshot: ProjectMap): string[] {
  const entries = Object.entries(snapshot.changeImpact)
    .filter(([, impact]) => impact.impacts.length > 0)
    .slice(0, 8);

  if (entries.length === 0) {
    return ["No change impact metadata detected yet."];
  }

  return entries.map(([file, impact]) =>
    `- ${file}: impacts ${impact.impacts.join(", ")}`
  );
}

function renderList(values: string[]): string[] {
  if (values.length === 0) {
    return ["No recommended path detected yet."];
  }

  return values.map((value, index) => `${index + 1}. ${value}`);
}
