import type { ProjectMap } from "../analyzers/projectMap.js";
import type { OnboardingLanguage, OnboardingModel, ReadingItem, FlowBlock } from "./model.js";

export function buildOnboardingModel(
  snapshot: ProjectMap,
  language: OnboardingLanguage
): OnboardingModel {
  return {
    language,
    project: {
      name: snapshot.project.name || "This project",
      language: snapshot.project.language !== "unknown" ? snapshot.project.language : null,
      framework: snapshot.project.framework !== "unknown" ? snapshot.project.framework : null,
      packageManager: snapshot.project.packageManager || null
    },
    overview: buildOverview(snapshot, language),
    mentalModel: buildMentalModel(snapshot, language),
    mainConcepts: buildMainConcepts(snapshot, language),
    importantAreas: buildImportantAreas(snapshot, language),
    keyFlows: buildKeyFlows(snapshot, language),
    whereToStart: buildWhereToStart(snapshot, language),
    generatedBy: language === "id"
      ? "Dibuat oleh DevMap dari `.devmap/snapshot.json`."
      : "Generated by DevMap from `.devmap/snapshot.json`."
  };
}

function buildOverview(
  snapshot: ProjectMap,
  language: OnboardingLanguage
): string {
  const lines: string[] = [];

  const name = snapshot.project.name || (language === "id" ? "Project ini" : "This project");
  const frameworkDesc = describeProjectFrameworks(snapshot, language);
  const projectLanguage = snapshot.project.language !== "unknown"
    ? language === "id" ? `menggunakan ${snapshot.project.language}` : snapshot.project.language
    : null;
  const features = snapshot.features.map((f) => f.name);
  const services = snapshot.externalServices;
  const entryPoint = snapshot.entryPoints[0];

  if (language === "id") {
    lines.push(
      `${name} adalah project ${[projectLanguage, frameworkDesc].filter(Boolean).join(" ") || "software"} yang dipetakan dari snapshot DevMap.`
    );
    if (features.length > 0) {
      lines.push(
        `Area utamanya terlihat dari fitur terdeteksi seperti ${formatInlineList(features, "id")}.`
      );
    } else {
      lines.push(
        "Snapshot belum mendeteksi fitur domain yang kuat, jadi guide ini fokus pada entry point dan file penting yang tersedia."
      );
    }
    if (entryPoint) {
      lines.push(
        `Untuk memahami cara project berjalan, mulai dari entry point ${entryPoint}, lalu ikuti file yang terhubung dengannya.`
      );
    }
    if (services.length > 0) {
      lines.push(
        `Project ini juga terhubung ke external service seperti ${formatInlineList(services, "id")}, jadi bagian integrasi perlu dibaca dengan hati-hati.`
      );
    }
  } else {
    const langFw = [projectLanguage, frameworkDesc].filter(Boolean).join(" ");
    lines.push(
      `${name} is a ${langFw || "software"} project mapped from the DevMap snapshot.`
    );
    if (features.length > 0) {
      lines.push(
        `Its main areas include detected features such as ${formatInlineList(features, "en")}.`
      );
    } else {
      lines.push(
        "The snapshot does not show strong domain features yet, so this guide focuses on entry points and important files."
      );
    }
    if (entryPoint) {
      lines.push(
        `To understand how the project runs, start from ${entryPoint}, then follow the files connected to it.`
      );
    }
    if (services.length > 0) {
      lines.push(
        `The project also integrates with external services such as ${formatInlineList(services, "en")}, so integration files deserve extra care.`
      );
    }
  }

  return lines.slice(0, 5).join("\n");
}

function buildMentalModel(snapshot: ProjectMap, language: OnboardingLanguage): string[] {
  const hasCli = hasScope(snapshot, "cli") || hasPathSegment(snapshot, "commands");
  const hasRoutes = snapshot.routes.length > 0 || snapshot.apiRoutes.length > 0;
  const hasDatabase = Boolean(snapshot.database);

  if (hasCli) {
    return language === "id" ? [
      "User menjalankan CLI command.",
      "Command membaca konfigurasi dan menentukan proses yang dibutuhkan.",
      "Project files discan dan dianalisis menjadi Project Map.",
      "Hasil analisis disimpan sebagai Snapshot.",
      "Command lain memakai Snapshot untuk menjawab, membuat guide, atau memberi output."
    ] : [
      "User runs a CLI command.",
      "The command reads configuration and decides which process is needed.",
      "Project files are scanned and analyzed into a Project Map.",
      "The analysis result is saved as a Snapshot.",
      "Other commands reuse the Snapshot to answer, guide, or render output."
    ];
  }

  if (hasRoutes) {
    const steps = (language === "id" ? [
      "User membuka route atau mengirim request.",
      snapshot.routes.length > 0 ? "Route UI merender halaman dan menghubungkan komponen terkait." : null,
      snapshot.apiRoutes.length > 0 ? "API route menjalankan business logic di sisi server." : null,
      hasDatabase ? "Data layer membaca atau menulis data yang dibutuhkan." : null,
      "Response dikembalikan ke user atau client."
    ] : [
      "User opens a route or sends a request.",
      snapshot.routes.length > 0 ? "UI routes render pages and connect related components." : null,
      snapshot.apiRoutes.length > 0 ? "API routes run server-side business logic." : null,
      hasDatabase ? "The data layer reads or writes the required data." : null,
      "A response is returned to the user or client."
    ]).filter((line): line is string => Boolean(line));
    return steps.slice(0, 10);
  }

  if (snapshot.entryPoints.length > 0) {
    return language === "id" ? [
      "Runtime masuk melalui entry point project.",
      "Entry point memanggil module utama yang terhubung lewat import.",
      "File penting dan feature-related files menjelaskan responsibility utama.",
      "Output akhir mengikuti framework atau runtime yang dipakai project."
    ] : [
      "Runtime starts from the project entry point.",
      "The entry point calls main modules connected through imports.",
      "Important files and feature-related files explain the main responsibilities.",
      "The final output follows the framework or runtime used by the project."
    ];
  }

  return language === "id" ? [
    "Snapshot belum punya flow runtime yang kuat.",
    "Mulai dari file penting dan dependency yang terdeteksi sebelum membuka area lain."
  ] : [
    "The snapshot does not expose a strong runtime flow yet.",
    "Start from important files and detected dependencies before opening other areas."
  ];
}

function buildMainConcepts(snapshot: ProjectMap, language: OnboardingLanguage): string[] {
  const concepts: string[] = [];

  for (const feature of snapshot.features.slice(0, 4)) {
    const desc = describeFeatureConcept(feature, language);
    const reason = feature.entryPoint
      ? language === "id"
        ? `Penting karena punya entry point ${feature.entryPoint}.`
        : `It matters because it has entry point ${feature.entryPoint}.`
      : language === "id"
        ? "Penting karena beberapa file snapshot mengarah ke area ini."
        : "It matters because multiple snapshot files point to this area.";

    concepts.push(`### ${feature.name}`, "", desc, "", reason, "");
  }

  if (snapshot.entryPoints.length > 0) {
    concepts.push(
      "### Entry Points",
      "",
      language === "id"
        ? "File tempat runtime, command, atau request mulai masuk ke project."
        : "Files where runtime, commands, or requests enter the project.",
      "",
      language === "id"
        ? "Ini membantu agent membuka file pertama yang benar sebelum membaca detail lain."
        : "This helps an agent open the right first file before reading details.",
      ""
    );
  }

  if (snapshot.routes.length > 0 || snapshot.apiRoutes.length > 0) {
    concepts.push(
      "### Routes",
      "",
      language === "id"
        ? "Mapping halaman atau API yang menjadi permukaan utama project."
        : "Page or API mappings that form the main project surface.",
      "",
      language === "id"
        ? "Routes menunjukkan bagaimana user atau client berinteraksi dengan sistem."
        : "Routes show how users or clients interact with the system.",
      ""
    );
  }

  if (snapshot.database) {
    concepts.push(
      "### Database Layer",
      "",
      language === "id"
        ? `Bagian project yang berhubungan dengan ${snapshot.database.provider}.`
        : `The project area connected to ${snapshot.database.provider}.`,
      "",
      language === "id"
        ? "Penting untuk memahami persistence, schema, dan risiko perubahan data."
        : "This matters for understanding persistence, schema, and data-change risk.",
      ""
    );
  }

  if (snapshot.externalServices.length > 0) {
    concepts.push(
      "### External Services",
      "",
      language === "id"
        ? `Integrasi ke service seperti ${formatInlineList(snapshot.externalServices, "id")}.`
        : `Integrations with services such as ${formatInlineList(snapshot.externalServices, "en")}.`,
      "",
      language === "id"
        ? "Area ini biasanya berkaitan dengan credential, network call, dan failure handling."
        : "This area usually involves credentials, network calls, and failure handling.",
      ""
    );
  }

  if (hasPathSegment(snapshot, "snapshot")) {
    concepts.push(
      "### Snapshot",
      "",
      language === "id"
        ? "Representasi hasil analisis project yang digunakan ulang oleh command lain."
        : "A reusable representation of project analysis used by other commands.",
      "",
      language === "id"
        ? "Mengurangi kebutuhan agent membaca repository dari nol setiap kali bekerja."
        : "It reduces the need for agents to reread the repository from scratch.",
      ""
    );
  }

  if (hasPathSegment(snapshot, "contextBuilder")) {
    concepts.push(
      "### Context Retrieval",
      "",
      language === "id"
        ? "Proses memilih file paling relevan sebelum AI menjawab pertanyaan."
        : "The process of selecting the most relevant files before AI answers.",
      "",
      language === "id"
        ? "Ini menjaga jawaban tetap fokus dan menghindari eksplorasi repository yang terlalu luas."
        : "It keeps answers focused and avoids broad repository exploration.",
      ""
    );
  }

  if (concepts.length === 0) {
    return [language === "id"
      ? "Belum ada konsep utama yang cukup kuat dari snapshot saat ini."
      : "No strong main concepts were detected from the current snapshot."];
  }

  return concepts.slice(0, 50);
}

function buildImportantAreas(snapshot: ProjectMap, language: OnboardingLanguage): ReadingItem[] {
  const items = new Map<string, ReadingItem>();
  const add = (path: string | undefined, priority: 1 | 2 | 3 | 4) => {
    if (!path || !hasFile(snapshot, path)) return;
    const existing = items.get(path);
    const item: ReadingItem = {
      path,
      priority: existing ? Math.min(existing.priority, priority) as 1 | 2 | 3 | 4 : priority,
      purpose: describeFilePurpose(path, snapshot, language),
      why: describeFileImportance(path, snapshot, language)
    };
    items.set(path, item);
  };

  for (const path of snapshot.entryPoints) add(path, 1);
  for (const path of snapshot.onboarding.recommendedPath.slice(0, 4)) add(path, 1);
  for (const file of snapshot.criticalFiles.slice(0, 6)) add(file.path, 1);
  for (const feature of snapshot.features) {
    add(feature.entryPoint, 2);
    for (const path of feature.files.slice(0, 4)) add(path, 2);
  }
  for (const flow of snapshot.flows.slice(0, 3)) {
    add(flow.entryPoint, 2);
    for (const step of flow.steps.slice(0, 4)) add(step.file, 2);
  }
  for (const [path, entry] of Object.entries(snapshot.fileIndex)) {
    if (["api", "service", "database", "config"].includes(entry.scope) || entry.featureRefs.length > 0) {
      add(path, 3);
    }
  }
  for (const path of snapshot.onboarding.recommendedPath) add(path, 4);

  const result = Array.from(items.values());
  result.sort((a, b) => {
    const aScore = fileSortScore(a.path, snapshot);
    const bScore = fileSortScore(b.path, snapshot);
    if (bScore !== aScore) return bScore - aScore;
    return a.path.localeCompare(b.path);
  });

  return result;
}

function buildKeyFlows(snapshot: ProjectMap, language: OnboardingLanguage): FlowBlock[] {
  return snapshot.flows.slice(0, 3).map((flow) => ({
    name: flow.name,
    type: flow.type,
    entryPoint: flow.entryPoint ?? null,
    steps: flow.steps.slice(0, 8).map((step) => ({
      label: step.file ?? step.label,
      purpose: step.purpose ? describeFlowStepPurpose(step.file ?? step.label, step.purpose, language) : undefined
    }))
  }));
}

function buildWhereToStart(snapshot: ProjectMap, language: OnboardingLanguage): string[] {
  const firstFiles = snapshot.onboarding.recommendedPath.slice(0, 3);
  const lines = language === "id" ? [
    "Jika baru pertama kali masuk project ini:",
    "",
    "1. Baca `DEVMAP.md` untuk memahami cara memakai Snapshot dan aturan agent.",
    "2. Pahami Mental Model di atas sebelum membuka source file.",
    firstFiles.length > 0
      ? `3. Buka ${formatInlineList(firstFiles, "id")} sebagai file awal.`
      : "3. Mulai dari entry point atau critical file yang tersedia di snapshot.",
    "4. Ikuti Flow Penting atau feature entry point yang paling dekat dengan task.",
    "5. Baru buka file tambahan jika Snapshot belum cukup menjawab pertanyaan."
  ] : [
    "If this is your first time in the project:",
    "",
    "1. Read `DEVMAP.md` to understand how to use the Snapshot and agent rules.",
    "2. Understand the Mental Model above before opening source files.",
    firstFiles.length > 0
      ? `3. Open ${formatInlineList(firstFiles, "en")} as the first source files.`
      : "3. Start from the entry point or critical files available in the snapshot.",
    "4. Follow the Key Flows or the feature entry point closest to your task.",
    "5. Only open extra files when the Snapshot is not enough."
  ];

  return lines;
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

function describeProjectFrameworks(
  snapshot: ProjectMap,
  language: OnboardingLanguage
): string | null {
  if (snapshot.project.framework !== "unknown") {
    return language === "id"
      ? `berbasis ${snapshot.project.framework}`
      : `built with ${snapshot.project.framework}`;
  }

  if (snapshot.project.frameworks.length > 0) {
    const frameworks = snapshot.project.frameworks.join(", ");
    return language === "id"
      ? `dengan framework workspace ${frameworks}`
      : `with workspace frameworks ${frameworks}`;
  }

  return null;
}

function describeFeatureConcept(
  feature: ProjectMap["features"][number],
  language: OnboardingLanguage
): string {
  if (feature.purpose && !isLowValuePurpose(feature.purpose)) return feature.purpose;
  if (feature.entryPoint) {
    return language === "id"
      ? `Area ${feature.name} dimulai dari ${feature.entryPoint} dan terhubung ke file pendukung yang terdeteksi di snapshot.`
      : `${feature.name} starts from ${feature.entryPoint} and connects to supporting files detected in the snapshot.`;
  }
  if (feature.files.length > 0) {
    return language === "id"
      ? `Area ${feature.name} terlihat dari beberapa file terkait di snapshot.`
      : `${feature.name} appears across several related files in the snapshot.`;
  }
  return language === "id"
    ? `Area ${feature.name} terdeteksi sebagai konsep penting dalam project.`
    : `${feature.name} is detected as an important project concept.`;
}

function describeFilePurpose(path: string, snapshot: ProjectMap, language: OnboardingLanguage): string {
  const entry = snapshot.fileIndex[path];
  const featureRefs = entry?.featureRefs ?? [];
  const critical = snapshot.criticalFiles.find((file) => file.path === path);

  if (entry?.purpose && !isLowValuePurpose(entry.purpose)) return entry.purpose;
  if (snapshot.entryPoints.includes(path)) {
    return language === "id"
      ? "Menjadi titik awal runtime atau command utama project."
      : "Acts as a runtime or command entry point for the project.";
  }
  if (featureRefs.length > 0) {
    return language === "id"
      ? `Mendukung area fitur ${formatInlineList(featureRefs, "id")}.`
      : `Supports the ${formatInlineList(featureRefs, "en")} feature area.`;
  }
  if (critical) {
    return language === "id"
      ? "Menghubungkan beberapa bagian penting dalam project."
      : "Connects important parts of the project.";
  }
  if (entry?.scope && entry.scope !== "unknown") {
    return language === "id"
      ? `Menangani responsibility ${entry.scope} dalam struktur project.`
      : `Handles the ${entry.scope} responsibility in the project structure.`;
  }
  return language === "id"
    ? "Membantu melengkapi konteks project berdasarkan snapshot."
    : "Helps complete project context from the snapshot.";
}

function describeFileImportance(path: string, snapshot: ProjectMap, language: OnboardingLanguage): string {
  const entry = snapshot.fileIndex[path];
  const impact = snapshot.changeImpact[path];
  const critical = snapshot.criticalFiles.find((file) => file.path === path);

  if (snapshot.entryPoints.includes(path)) {
    return language === "id"
      ? "File ini menjelaskan bagaimana eksekusi project dimulai."
      : "This file explains how project execution starts.";
  }
  if (entry?.featureRefs.length) {
    return language === "id"
      ? `File ini memberi konteks langsung untuk ${formatInlineList(entry.featureRefs, "id")}.`
      : `This file gives direct context for ${formatInlineList(entry.featureRefs, "en")}.`;
  }
  if (impact?.impacts.length) {
    return language === "id"
      ? `Perubahan di sini dapat memengaruhi ${formatInlineList(impact.impacts, "id")}.`
      : `Changes here can affect ${formatInlineList(impact.impacts, "en")}.`;
  }
  if (impact?.dependents.length) {
    return language === "id"
      ? "Banyak bagian project bergantung pada file ini."
      : "Several project areas depend on this file.";
  }
  if (critical) {
    return language === "id"
      ? "Snapshot menandai file ini sebagai critical karena perannya dalam struktur project."
      : "The snapshot marks this file as critical because of its structural role.";
  }
  return language === "id"
    ? "File ini membantu agent memahami konteks sebelum membuka detail yang lebih kecil."
    : "This file helps an agent understand context before opening smaller details.";
}

function describeFlowStepPurpose(
  label: string,
  purpose: string | undefined,
  language: OnboardingLanguage
): string | undefined {
  if (purpose && !isLowValuePurpose(purpose)) return purpose;
  return undefined;
}

function formatInlineList(values: string[], language: OnboardingLanguage): string {
  const uniqueValues = [...new Set(values)].slice(0, 4);
  if (uniqueValues.length <= 1) return uniqueValues[0] ?? "none";
  const conjunction = language === "id" ? "dan" : "and";
  return `${uniqueValues.slice(0, -1).join(", ")} ${conjunction} ${uniqueValues.at(-1)}`;
}

function isLowValuePurpose(purpose: string): boolean {
  return /\b(exposes|contains project code|identifies .* capability)\b/i.test(purpose);
}

function hasScope(snapshot: ProjectMap, scope: string): boolean {
  return Object.values(snapshot.fileIndex).some((entry) => entry.scope === scope);
}

function hasPathSegment(snapshot: ProjectMap, segment: string): boolean {
  const normalizedSegment = segment.toLowerCase();
  return Object.keys(snapshot.fileIndex).some((path) =>
    path.toLowerCase().includes(normalizedSegment)
  );
}

function hasFile(snapshot: ProjectMap, path: string): boolean {
  return Boolean(snapshot.fileIndex[path])
    || snapshot.entryPoints.includes(path)
    || snapshot.criticalFiles.some((file) => file.path === path)
    || snapshot.onboarding.recommendedPath.includes(path);
}

function fileSortScore(path: string, snapshot: ProjectMap): number {
  const entry = snapshot.fileIndex[path];
  const critical = snapshot.criticalFiles.find((file) => file.path === path);
  return (entry?.importance ?? 0)
    + (critical?.score ?? 0)
    + (snapshot.entryPoints.includes(path) ? 100 : 0)
    + ((entry?.featureRefs.length ?? 0) * 20);
}
